from telebot import TeleBot, types

bot = TeleBot(token='6269415190:AAGUYKqHYXOCk4viu8aTOehKIxdKpdzM-gg', parse_mode='html')

DEFINITOINS = {
'bear with a sore head': 'Irritated, bad mood',
'bit of a dark horse': 'Person with hidden abilities',
'bitter pill to swallow': 'A difficult fact to accept',
'different kettle of fish': 'A totally different sitation from the one just mentioned',
'lead a dog\'s life': 'A difficult, hard life',
'fish out of water': 'Somebody who feels uncomfortable',
'long shot': 'A wild guess; a risk',
'memory like a sieve': 'A poor memory',
'night owl': 'Person who enjoys staying up late',
'pain in the neck': 'Annoying person/thing',
'piece of cake': 'Something very easy to do',
'red rag to a bull': 'Action, comment, etc. liable to provoke somebody',
'red-letter day': 'A very important day',
'sitting duck': 'An easy target',
'storm in a teacup': 'A lot of fuss about something that is not important',
'wild-goose chase': 'A hopeless search',
'above board': 'Honest',
'achilles heel': 'Weakest point of somebody\'s character',
'against all odds': 'Despite the difficulties',
'agree to disagree': 'Stop arguing because there is no chance of agreement',
'all along': 'From the beginning until now',
'all but': 'Nearly, almost',
'all ears': 'Awaiting an explanation',
'all in': 'Exhausted',
'all in all': 'When everything is considered',
'all the same': 'Yet, however',
'all told': 'Altogether; in total',
'old wives\' tale': 'False belief',
'unknown quantity': 'Person or thing that one has no experience of',
'as a last resort': 'When all else has failed',
'as the crow flies': 'In a direct line; by a direct route',
'at close quarters': 'From a short distance',
'at large': 'Free, not caught',
'at the cutting edge': 'At the forefront of',
'bark up the wrong tree': 'Have a false idea about something',
'ahead of one\'s time': 'Have modern ideas',
'all at sea': 'Be in a state of confusion',
'all fingers and thumbs': 'Awkward, clumsy',
'all very well': 'Appear satisfactory but in fact not be',
'as busy as a bee': 'Very busy',
'as thick as a brick': 'Stupid',
'beside oneself with anger': 'To be extremely angry',
'born yesterday': 'Easily deceived, naive',
'dying for something': 'Really want something',
'fit for': 'Be good enough for',
'for the high jump': 'About to be punished',
'full of beans': 'Very lively',
'green': 'Inexperienced',
'in a quandary': 'Confused; undecided',
'in somebody\'s black books': 'Out of favour',
'in somebody\'s shoes': 'In somebody\'s position',
'in the dark about something': 'Unaware of something',
'in the doghouse': 'Out of favour, in trouble',
'in the know': 'Well-informed',
'in the same boat': 'In the same (usually bad) situation',
'in two minds about something': 'Not be able to decide what to do',
'on the cards': 'Likely to happen',
'on the defensive': 'Protect oneself because one feels insecure or threatened',
'on the up and up': 'Improve steadily',
'out of practice': 'Lacking practice',
'over the moon': 'Be elated',
'second to none': 'The best',
'sound asleep': 'Sleep deeply',
'the apple of somebody\'s eye': 'Very precious to somebody; be somebody\'s favourite',
'the perfect image of somebody': 'Look exactly like somebody',
'the splitting image of somebody': 'Look exactly like somebody',
'thrown off balance': 'Surprised',
'tickled pink': 'Really pleased',
'up and about': 'Have recovered from an illness',
'up in arms': 'Very angry',
'worn out': 'Very tired',
'soaked to the skin': 'Very wet',
'close shave': 'Barely avoid an accident/a bad situation',
'bad apple': 'Troublemaker or undesirable person in a group',
'bear fruit': 'Be successful',
'beat around the bush': 'Avoid saying what one means directly',
'before one can say Jack Robinson': 'Extremely quickly',
'beg the question': 'Makes people want to ask a particular question',
'behind bars': 'In prison',
'behind the scenes': 'In secret',
'below the belt': 'Cruel and unfair',
'best of both worlds': 'Enjoying the advantage of two things simultaneously',
'bide one\'s time': 'Wait for a good opportunity',
'big cheese': 'Person with important job/position',
'big-headed': 'Conceited; boastful',
'bite off more than somebody can chew': 'Try to do something which is too difficult',
'black and blue all over': 'Covered with bruises',
'black tie': 'Formal clothing',
'blaze a trail': 'Discover something new',
'blessing in disguise': 'Something which appears bad at first but then turns out favourably',
'blow a fuse': 'Become very angry',
'blue-eyed boy': 'A favoured person',
'bolt from the blue': 'Suddenly',
'born with a silver spoon in one\'s mouth': 'Born into a rich and affluent family',
'brainwave': 'Sudden clear idea/thought',
'break even': 'Show neither loss nor profit',
'break the ice': 'Ease the tensione when one first meets people',
'bring home the bacon': 'Bring home the bacon',
'bring something home to somebody': 'Make somebody understand how important or serious something is',
'bring to one\'s knees': 'Destroy, humble',
'browned off': 'Fed up; bored',
'bury one\'s head in the sand': 'Avoid or ignore reality/responsibility',
'butter somebody up': 'Flatter somebody',
'by and large': 'Generally speaking',
'by definition': 'Having a quality simply because of what it is',
'by force of habit': 'Used to doing something without thinking',
'by trial and error': 'Learning from one\'s mistakes',
'by the skin of one\s teeth': 'Only just succeed',
'bun in the oven': 'Pregnant',
'call it quits': 'Give up/stop',
'call it a day': 'Stop doing something for a while or until the next day',
'call somebody names': 'Insult somebody',
'cast aspersions': 'Criticise',
'catch somebody red-handed': 'Be caught while committing a crime',
'chase rainbows': 'Try to achieve something that is very difficult; impossible or very desirable',
'chair a meeting': 'Preside over a meeting',
'chip off the old block': 'Somebody who is very like one of his parents',
'chop and change': 'Keep changing (your mind)',
'claim to fame': 'Thing which makes somebody unusual',
'clear the air': 'Remove suspicion/bad feeling',
'close to home': 'A comment that is true and makes you uncomfortable',
'come clean': 'Admit the truth',
'come out of one\'s shell': 'Gain personal confidence',
'come to a head': 'Reach a critical point',
'come to a standstill': 'Not progress/stop',
'come to terms with': 'Accept a difficult situation',
'come to the fore': 'Become important or popular',
'come to the point': 'Reach the main point in a discussion',
'cook one\'s goose': 'End one\'s plans abruptly',
'cost a bomb': 'Very expensive',
'cost an arm and a leg': 'Very expensive',
'cramp one\'s style': 'Restrict one\'s behaviour in some way',
'crocodile tears': 'False tears',
'cross one\'s mind': 'Think of something',
'cry over spilt milk': 'Grieve over something that can\'t be put right',
'cut corners': 'Be less thorough',
'cut somebody dead': 'Ignore somebody',
'cut somebody to the quick': 'Deeply hurt somebody\'s feelings',
'cut to the bone': 'Reduced to the minimum',
'deal a blow to': 'Damage one\'s hopes',
'different as chalk and cheese': 'Totally different',
'does it show?': 'Is it obvious?',
'dog eat dog': 'Ruthless competition, rivalry',
'dog-eared': '(of books) with the corners bent and turned down through use',
'don\'t give up your day job': 'Continue to do something you know rather than trying something new',
'don\'t hold your breath': 'Don\'t wait for somebody/something anxiously',
'donkey work': 'Boring, monotonous work',
'donkey\'s years': 'A long time',
'down in the dumps': 'Depressed/miserable',
'down the drain': 'Wasted; lost',
'drive a hard bargain': 'Be a tough businessman',
'drive somebody up the wall': 'Make somebody angry/annoy somebody',
'drop a brick': 'Say something tactlessly',
'drop somebody a line': 'Send somebody a letter',
'ease off': 'Reduce in degree, speed or intensity',
'eat one\'s heart out': 'Feel jealous/ sad about something',
'every nook and cranny': 'Everywhere',
'every cloud has a silver lining': 'Be optimistic',
'face the music': 'Be criticised or punished for something you have done',
'fair and square': 'Within the rules',
'fall head over heels': 'Fall in love quickly',
'fall into place': 'Become clear',
'feel down in the mouth': 'Feel discouraged/depressed',
'feel in one\s bones': 'Feeling something instinctively',
'feel one\'s ears burning': 'Have a feeling that somebody is talking about you',
'few and far between': 'Scarce/rare',
'fight like cat and dog': 'Disagree violently',
'fine kettle of fish': 'Confused state of affairs',
'flat broke': 'Penniless',
'flog a dead horse': 'Waste time doing something useless',
'fly off the handle': 'Quickly become very angry',
'fly on the wall': 'See/hear something in a situation which does not involve you',
'for all': 'In spite of',
'for all I care': 'I don\'t care',
'for all I know': 'As far as I know',
'for donkey\'s years': 'For a very long time',
'for the time being': 'Temporarily',
'frosty welcome': 'Unfriendly reception',
'gatecrasher': 'Somebody attending a party without an invitation',
'get a bit hot under the collar': 'Get angry, upset or embarassed',
'get a move on': 'Hurry up',
'get a problem off one\'s chest': 'Tell somebody else about your problem',
'get cold feet': 'Lose courage to do something; be nervous or frightened because something might fail',
'get nowhere fast': 'Make no progress',
'get off on the wrong foot': 'Argue or disagree at the beginning of a relationship',
'get on one\'s nerves': 'Irritate/annoy somebody',
'get out of bed on the wrong side': 'Be in a bad mood',
'get out of hand': 'Become out of control',
'get the hang of it': 'Get in the habit of doing something',
'get the sack': 'Be dismissed from one\'s job',
'get the wrong end of the stick': 'Misunderstand completely what has been said',
'get wind of': 'Receive information about something indirectly',
'get your own back': 'Take/get revenge',
'give and take': 'Compromise',
'give chapter and verse': 'Give every exact detail',
'give somebody the cold shoulder': 'Ignore somebody',
'give somebody the slip': 'Escape from somebody',
'give the green light to something': 'Give permission to proceed with something',
'give vent to': 'Express something freely',
'give way to': 'Give in/yield',
'go back on one\s word': 'Not fulfil a promise',
'go by the board': 'Be rejected',
'go for a song': 'Be sold very cheaply',
'go to any lengths': 'Do anything necessary to get something you want',
'go to one\'s head': 'Make conceited',
'go to the dogs': 'Worsen',
'go without saying': 'Be a foregone conclusion',
'golden opportunity': 'The best chance to gain something',
'grease somebody\'s palm': 'Bribe somebody',
'green belt': 'The area on the outskirts of a town adjoining the country',
'green with envy': 'Very jealous',
'grey matter': 'Brains; intelligence',
'grow out of something': 'Become too big for something',
'hand in glove with somebody': 'Be in very close contact with somebody',
'have a bee in one\'s bonnet': 'Have an obsession about something',
'have a frog in one\'s throat': 'Inability to speak due to nervousness',
'have a job to do something': 'Find something difficult to do',
'have a sharp tongue': 'Tend to say unkind or hurtful things',
'have a yellow streak': 'Be a coward',
'have an early night': 'Go to bed early',
'have an eye for': 'Be good at judging the worth of something',
'have at one\'s fingertips': 'Have easily available',
'have butterflies in one\'s stomach': 'Be very nervous about something',
'have kittens': 'Be nervous/anxious about something',
'have many irons in the fire': 'Have lots of plans in progress at the same time',
'have no fixed abode': 'Be homeless',
'have no option but': 'Must; have no choice',
'have one\'s heart in one\'s mouth': 'Be extremely anxious about something',
'have somebody\'s hands full': 'Be very busy with something',
'have the cheek': 'Dare to do something',
'have the gift of the gab': 'Be able to talk well',
'have time on one\'s hands': 'Have free time',
'have words with somebody': 'Have an argument',
'hear it through the grapevine': 'Find out information indirectly',
'hit the nail on the head': 'Say exactly the right thing',
'hit the roof': 'Get very angry',
'hit the sack': 'Go to bed',
'hold one\'s horses': 'Wait; be patient',
'ill at ease': 'Embarassed; uncomfortable',
'in a flash': 'Very quickly',
'in a nutshell': 'Briefly; in few words',
'in a rut': 'Be stuck in a monotonous routine',
'in a tick': 'Shortly, soon',
'in abeyance': 'Halted temporarily',
'in arrears': 'Have not paid the money they owe',
'in black and white': 'In writing or in print; absolutely right or wrong',
'in broad daylight': 'In full view of the public',
'in clover': 'Living a luxurious and comfortable life',
'in deep water': 'In trouble/difficulty',
'in full flow': 'Talking at length',
'in public': 'In the presence of other people',
'in the abstract': 'In a general way',
'in the act of': 'While performing the act',
'in the air': 'Uncertain',
'in the bag': 'Something that is assured or a guaranteed success',
'in the balance': 'Uncertain',
'in the black': 'Not owing anybody any money',
'in the flesh': 'In person',
'in the long run': 'After a long period of time',
'in the nick of time': 'Just in time',
'in the offing': 'Likely to happen',
'in the red': 'Owe money to a bank',
'it stands to reason': 'It is logical',
'it takes two to tango': 'Actions or communications need more than one person',
'it\'s all Greek to me': 'Something new or foreign; not easily understood',
'jack of all trades': 'Somebody who is able to do a variety of jobs',
'keep a straight face': 'Manage to look serious under difficult circumstances',
'keep an eye on something': 'Guard/protect something',
'keep in check': 'Control',
'keep one\'s chin up': 'Not be discouraged',
'keep one\'s fingers crossed': 'Hope that something will turn out well',
'keep one\'s wits about one': 'Be alert and able to deal with difficulties',
'keep oneself to oneself': 'Live quietly, privately',
'keep something quiet': 'Keep something secret',
'keep something under one\'s hat': 'Keep something secret',
'keep up with the Joneses': 'Compete with others in status/material goods',
'kick the bucket': 'Die',
'kill time': 'Pass time while waiting for somebody/something',
'kill two birds with one stone': 'Achieve two things with one action',
'know the ropes': 'Know all the details of something',
'lay bare': 'Make public',
'lay the table': 'Set the table for a meal',
'lend an ear': 'Listen to somebody in a careful and sympathetic way',
'lend somebody a hand': 'Give help to somebody',
'let sleeping dogs lie': 'Avoid mentioning a subject which could cause trouble',
'let the cat out of the bag': 'Reveal a secret',
'lights are on but nobody is home': 'Someone is stupid or lacking intelligence',
'like a bull in a china shop': 'Behave in a clumsy/awkward way',
'like the back of one\'s hand': 'Be very familiar with something',
'like water off a duck\'s back': 'Having no effect',
'live out of a suitcase': 'Travel often/not have a permanent home',
'look at something though rose-coloured spectacles': 'See something from an unrealistically positive point of view',
'look down one\'s nose at somebody': 'Feel/act superior to somebody',
'look the other way': 'To deliberately ignore something bad that is happening',
'lose heart': 'Become discouraged',
'lose one\'s head': 'Lose self-control',
'lose one\'s nerve': 'Lose courage',
'lost cause': 'Hopeless situation or case',
'make a clean breast of': 'Confess',
'make a dog\'s dinner': 'Make a mess of something',
'make a flying visit': 'Make a quick trip',
'make a fool of oneself': 'Make oneself look stupid',
'make a killing': 'Have a sudden, great success',
'make a living': 'Earn money',
'make a mountain out of a molehill': 'Cause a fuss about a trivial matter',
'make a name for oneself': 'Become famous/respected for something',
'make allowances for': 'Take special circumstances into consideration',
'make amends for': 'Try to compensate for a past action',
'make common cause with somebody': 'Act together to achieve aim',
'make hay while the sun shines': 'Take advantage of favourable circumstances',
'make head nor tail of': 'Understand something',
'make light of': 'Treat something as unimportant',
'make money hand over fist': 'Make a lot of money quickly and easily',
'make one\'s blood boil': 'Cause somebody to become very angry',
'make one\'s getaway': 'Escape',
'make quite a scene': 'Become angry in a dramatic way',
'make somebody\'s day': 'Make somebody very happy',
'make waves': 'Cause trouble',
'match made in heaven': 'Two people perfectly suited to each other',
'meet behind closed doors': 'Meet secretly',
'moon around': 'Look miserable',
'more to somebody than meets the eye': 'Somebody is more important or interesting than is first seen',
'murphy\'s law': 'anything that can go wrong will go wrong',
'mutton dressed as a lamb': 'Dress in a style younger than or inappropriate to your age',
'no room to swing a cat': 'No room at all',
'not all it\'s cracked up to be': 'Not as good as people say it is',
'not be one\'s cup of tea': 'Not suit one\'s taste',
'not count one\'s chickens before they\'re hatched': 'Not assume something before it happens',
'not have it both ways': 'Refuse to make a decision between two pleasant things',
'not have the foggiest idea': 'Not know something at all',
'not hold water': 'Not seem reasonable or in accordance with the facts',
'not lose any sleep over something': 'Not worry about something',
'null and void': 'Invalid; not legally binding',
'of all people': 'Used to express annoyance/surprise',
'of its own accord': 'Automatically',
'of no consequence': 'Of no value',
'off colour': 'Look/be slightly unwell',
'off the cuff': 'Without preparation',
'off the point': 'Irrelevant',
'off the record': 'Unofficial(ly)',
'on a shoe string': 'On a very small budget',
'on account of': 'Because of',
'on edge': 'Tense/nervous/anxious',
'on no account': 'Under/in no circumstances',
'on second thoughts': 'Having changed one\'s mind',
'on the air': 'Broadcasting',
'on the alert': 'Watchful and prepared',
'on the ball': 'Alert',
'on the blink': 'Stop working properly (of electrical equipment)',
'on the dole': 'Receiving unemployment benefit/social security',
'on the dot': 'Punctual, exact on time',
'on the face of it': 'Judging by how something appears',
'on the level': 'Honest/sincere',
'on the quiet': 'Secretly',
'on the spur of the moment': 'Without thinking about something',
'on this/that account': 'For this/that reason',
'once and for all': 'For the last time',
'once in a blue moon': 'Very rarely',
'one\'s flesh and blood': 'Family member',
'open to debate': 'Not decided/settled',
'out and about': 'Outdoors; travelling from one place to another',
'out in the open': '(of secrets) revealed, known',
'out of bounds': 'prohibited, forbidden (place)',
'out of print': '(of books) not available anymore',
'out of the blue': 'Suddenly and unexpectedly',
'out of the frying pan into the fire': 'From a situation to a worse/similar one',
'out of the question': 'Impossible',
'out of turn': 'Not in the correct order/time',
'out-and-out': 'Complete, total',
'paint the town red': 'Have a great time',
'part and parcel of': 'Basic part of',
'part company with': 'End association',
'pay somebody\'s way': 'Contribute your shares of a bill',
'pick someone\'s brains': 'Ssk somebody to help with a problem',
'pitch black': 'Very dark',
'play cat and mouse with somebody': 'Keep somebody in a state of uncertain expectation treating them alternatively cruelly and kindly',
'play it by ear': 'Act in a situation by responding to events rather than according to plan',
'play one\'s cards right': 'Act cleverly',
'play truant': 'Stay away from school without permission',
'plenty more fish in the sea': 'Many more opportunities in life for love',
'point the finger of suspicion': 'Blame somebody for something',
'pop the question': 'Make a proposal of marriage',
'pull a few strings': 'Use influential contacts in order to obtain an advantage',
'pull one\'s leg': 'Tease or trick somebody',
'pull one\'s socks up': 'Make a greater effort',
'pull the plug': 'Terminate or discontinue something',
'put a damper on': 'Ruin something or make it less enjoyable',
'put all eggs in one basket': 'Make everything dependent on only one thing',
'put down roots': 'Settle down',
'put on a brave face': 'Try to hide one\'s disappointment',
'put one\'s foot down': 'Insist on something',
'put one\'s foot in it': 'Make a tactless comment',
'put one\'s heart and soul into something': 'Be devoted to something',
'put somebody\'s name forward': 'Nominate somebody',
'put the cat among the pigeons': 'Cause trouble/controversy',
'put two and two together': 'Arrive at the truth by looking at facts',
'put words into one\'s mouth': 'Pretend that somebody has said something that they haven\'t actually said',
'rack somebody\'s brains': 'Think very hard about something',
'raining cats and dogs': 'Rain heavily',
'red flag': 'Signal or indication that something is not working properly of correctly',
'red herring': 'Something which distracts you from something important',
'red tape': 'Unnecessary bureaucracy',
'ring a bell': 'Remind somebody of something',
'rise to the challenge': 'Act and be successful even though something is new',
'see eye to eye with somebody': 'Agree with somebody',
'see fit': 'Think suitable or right',
'see red': 'Suddenly become very angry',
'see the back of': 'Be glad to see somebody leave',
'set in one\'s ways': 'Fixed in one\'s habits',
'ship has sailed': 'A particular opportunity has passed and is no longer available',
'shed light upon': 'Give new/further information',
'short and sweet': 'Brief but pleasant (usually ironic)',
'show one\'s true colours': 'Reveal one\'s real character',
'sleep like a dog': 'Be sound asleep',
'sleep on it': 'Think about something',
'slip one\'s mind': 'Forget about something',
'slow on the uptake': 'Slow to understand',
'smell a rat': 'Suspect that something is wrong',
'sour grapes': 'Say unpleasant comments because of jealousy',
'speak volumes': 'Be strong evidence of somebody\'s feelings or merits',
'speak of the devil': 'When the person you have just been talking about arrives',
'spill the beans': 'Reveal a secret/the facts',
'stand in somebody\'s way': 'Prevent somebody from doing something',
'status symbol': 'Property/possession that shows somebody\'s high social rank, wealth, etc.',
'stay clear of': 'Avoid somebody/something',
'stew in one\'s own juice': 'Suffer the consequences of one\'s own action',
'something comes in handy': 'Very useful/practical',
'straight from the horse\'s mouth': 'From the most direct source',
'strike a chord': 'Make somebody feel sympathy',
'strike gold': 'Come across something useful',
'sweet tooth': 'Enjoy eating sweet things',
'swim like a fish': 'Swim very well',
'take it easy': 'Not work too hard/relax',
'take one\'s time': 'Not to hurry',
'take somebody for granted': 'Not appreciate somebody',
'take something into account': 'Consider something',
'take something on the chin': 'Bravely accept criticism',
'take something to heart': 'Take personally/be influenced by',
'take something with a pinch of salt': 'Not believe something completely',
'take the bull by the horns': 'Deal with something boldly and directly',
'take things to pieces': 'Dismantle things',
'take to one\'s heels': 'Run away',
'talk the hind legs off a donkey': 'Talk for a long time, uninterrupted',
'teacher\'s pet': 'Teacher\'s favourite student',
'black sheep of the family': 'A disgraced family member',
'ins and outs': 'The details of an activity',
'last straw': 'The last and worst episode in a chain of bad experiences',
'life and soul of something': 'The most lively and amusing person present somewhere',
'lion\'s share': 'The biggest part/portion',
'pot calling the kettle black': 'Accusing somebody of a fault one has oneself',
'rat race': 'The competitive nature of modern urban life',
'tip of the iceberg': 'Small evident part of a much larger, concealed situation',
'year dot': 'A long time ago',
'thick-skinned': 'Insensitive',
'through thick and thin': 'Whatever happens',
'to no effect': 'Unsuccessful',
'tongue in cheek': 'Not serious, ironic',
'tooth and nail': 'Fiercely',
'touch and go': 'With uncertain result',
'tough cookie': 'Very determined person',
'turn a blind eye to something': 'Ignore',
'turn over a new leaf': 'Make a new start',
'under the weather': 'Depressed/unwell',
'until one is blue in the face': 'As hard/long as one possibly can',
'until the cows come home': 'For a long time',
'up and coming': 'Likely to be successful',
'up in the air': 'Existing, but not talked about',
'ups and downs': 'Good things with bad ones',
'wash somebody\'s hands of somebody': 'Refuse to be involved with somebody',
'wet behind the ears': 'Inexperienced',
'wet blanket': 'Dull person who spoils people\'s happiness',
'whet somebody\'s appetite': 'Make somebody eager to have/experience more',
'white elephant': 'Useless/unwanted possession',
'white-collar job': 'Office/clerical work',
'white lie': 'Little or harmless lie told to be polite and avoid hurting someone\'s feelings',
'with a view to doing something': 'With the intention or hope of doing something',
'with flying colours': 'With great success',
'without fail': 'Do something no matter what',
'work a miracle': 'Make something almost impossible happen',
'work to rule': 'Adhere strictly to the rules as a form of protest',
'your guess is as good as mine': 'Not knowing the answer',
}

@bot.message_handler(commands=['start'])
def start_command_handler(message: types.Message):
    bot.send_message(
        chat_id=message.chat.id,
        text='Привет! Я помогу тебе узнать значение различных идиом и фразеологизмов английского языка 🧐\nВведи интересующее тебя выражение.',
    )

@bot.message_handler()
def message_handler(message: types.Message):
    definition = DEFINITOINS.get(
        message.text.lower(),
    )
    if definition is None:
        bot.send_message(
            chat_id=message.chat.id,
            text='Такое выражение мне незнакомо 🤔',
        )
        return
    
    bot.send_message(
        chat_id=message.chat.id,
        text=f'Значение:\n{definition}',
    )

    bot.send_message(
        chat_id=message.chat.id,
        text=f'Что ещё тебя интересует?',
    )


def main():
    bot.infinity_polling()


if __name__ == '__main__':
    main()
